Repository harshAswani1109/welfare-wave, pull requests merged in 2023-06, with the labels that each got.

#4 try to fix qr
  components/donationCard.js
  components/qr.js
Labels: bug

#2 FAQ's added
  components/Accordion.js
  components/layout.js
  public/data.json
  public/down.svg
  public/favicon.ico
  public/minus.svg
  public/plus.svg
  public/up.svg
  src/pages/faq.js
Labels: documentation, enhancement

#5 footer added
  components/footer/footer.js
  components/navbar/navbar.js
  src/pages/contact.js
  src/pages/index.js
Labels: documentation

#6 Ha/navbar
  components/footer/footer.js
  components/navbar/dropdown.js
  components/navbar/navbar.js
  src/pages/education/culturalDiversity.js
  src/pages/education/environmental.js
  src/pages/education/financialLiteracy.js
  src/pages/education/healthEducation.js
  src/pages/education/legalRights.js
  src/pages/education/lifeSkillEducation.js
  src/pages/education/socialEmotional.js
Labels: documentation

#7 Ha/feat/education
  components/navbar/dropdown.js
  components/navbar/mobileNavbar.js
  components/navbar/navbar.js
  src/pages/education/culturalDiversity.js
  src/pages/education/environmental.js
  src/pages/education/financialLiteracy.js
  src/pages/education/healthEducation.js
  src/pages/education/legalRights.js
  src/pages/education/lifeSkillEducation.js
  src/pages/education/socialEmotional.js
Labels: documentation

#9 Ag/ayush
  components/footer/footer.js
  components/landing/landing.js
  components/landing/landingComponents/AboutUs.js
  components/landing/landingComponents/Carousal.js
  components/landing/landingComponents/CoreTeam.js
  components/landing/landingComponents/Donate.js
  components/landing/landingComponents/Hero.js
  components/landing/landingComponents/Stats.js
  components/navbar/dropdown.js
  components/navbar/mobileNavbar.js
  components/navbar/navbar.js
  package.json
  public/ab1.jpeg
  src/pages/about.js
  src/pages/contact.js
  yarn.lock
Labels: enhancement

#10 Ag/ayush
  components/landing/landing.js
  components/landing/landingComponents/AboutUs.js
  components/landing/landingComponents/Carousal.js
  components/landing/landingComponents/CoreTeam.js
  components/landing/landingComponents/Donate.js
  components/landing/landingComponents/Hero.js
  components/landing/landingComponents/Stats.js
  public/WhatsApp Image 2023-06-12 at 20.57.04.jpg
  public/ayush.jpg
  public/harsh.jpg
  public/qr.jpg
  public/qr_side.jpg
  public/sashikant.jpg
  public/suraj.jpg
Labels: enhancement
